# **Foundation Batch 2619 Assignment**

# **Business Case Scenario**

You are working as a Junior Data Analyst at RetailKart, an online retail company that sells consumer products across India.

The marketing team spends money on:

1. TV Advertising
2. Social Media
3. Advertising
4. Influencer Marketing
5. Discounts

The management wants to understand:

**“Which factors impact product sales the most?”**

Your task is to build a Multiple Linear Regression Model to (a) predict Sales Revenue based on different marketing and business variables and (b) find out which factor has most impact on sales.

## **Objective**

Build a Multiple Regression model to:

1. Analyze relationships between variables
2. Predict Sales Revenue
3. Identify important business factors affecting sales
4. Evaluate model performance

## **Dataset Information**

The dataset contains 500 rows and the following columns:

| Column Name | Description |
|---|---|
| TV_Ads | Money spent on TV ads (₹) |
| Social_Media_Ads | Money spent on social media ads (₹) |
| Influencer_Marketing | Money spent on influencer marketing (₹) |
| Discount_Percentage | Discount offered (%) |
| Website_Visits | Daily website visitors |
| Customer_Rating | Product rating (1–5) |
| Sales_Revenue | Total sales revenue (Target Variable) |

# Submission Guidelines
1. Email with your name and batch to support@ybifoundation.com

2. Last date 22nd May 2026, Friday

In [4]:
# Import libraray
import pandas as pd

In [5]:
# Read file
df = pd.read_csv('https://github.com/YBIFoundation/Assignmnet/raw/main/SalesPrediction.csv')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   TV_Ads                500 non-null    int64
 1   Social_Media_Ads      500 non-null    int64
 2   Influencer_Marketing  500 non-null    int64
 3   Discount_Percentage   500 non-null    int64
 4   Website_Visits        500 non-null    int64
 5   Customer_Rating       500 non-null    float64
 6   Sales_Revenue         500 non-null    int64
dtypes: float64(1), int64(6)
memory usage: 27.5 KB

In [7]:
df.head()

,TV_Ads,Social_Media_Ads,Influencer_Marketing,Discount_Percentage,Website_Visits,Customer_Rating,Sales_Revenue
0,25795,20305,19449,27,4155,4.9,232530
1,10860,14817,20520,33,9321,4.0,267866
2,86820,16261,29025,22,4814,4.0,157440
3,64886,5417,12535,35,14125,4.4,271086
4,16265,46576,28439,34,4216,4.5,55473

In [8]:
df.isnull().sum()

TV_Ads                  0
Social_Media_Ads        0
Influencer_Marketing    0
Discount_Percentage     0
Website_Visits          0
Customer_Rating         0
Sales_Revenue           0
dtype: int64

In [9]:
df.describe()

,TV_Ads,Social_Media_Ads,Influencer_Marketing,Discount_Percentage,Website_Visits,Customer_Rating,Sales_Revenue
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000,500.000000
mean,55825.006000,27143.736000,16195.064000,27.776000,10229.486000,3.76920,246770.528000
std,26748.293127,13134.923997,8243.270816,12.800372,5274.997944,0.71593,96009.977152
min,10206.000000,5009.000000,2060.000000,5.000000,1011.000000,2.50000,-25245.000000
25%,32596.250000,15737.500000,8931.750000,17.000000,5934.250000,3.17500,173714.250000
50%,58379.000000,26782.500000,16106.500000,28.000000,10043.500000,3.80000,246818.000000
75%,77983.500000,39633.500000,23521.500000,38.250000,14651.000000,4.40000,315504.250000
max,99912.000000,49912.000000,29965.000000,49.000000,19913.000000,5.00000,486332.000000

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X = df[['TV_Ads',
        'Social_Media_Ads',
        'Influencer_Marketing',
        'Discount_Percentage',
        'Website_Visits',
        'Customer_Rating']]

y = df['Sales_Revenue']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=2529
)

model = LinearRegression()
model.fit(X_train, y_train)

print("Training complete!")

Training complete!

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
import pandas as pd

y_pred = model.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

importance = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_
})

print("\nFeature Importance:")
print(importance.sort_values(by='Coefficient', ascending=False))

R2 Score: 0.8109380127080301
MAE: 33840.031475320466
MSE: 1823591480.853671
RMSE: 42703.53007485062

Feature Importance:
                Feature  Coefficient
5       Customer_Rating  7554.310617
3   Discount_Percentage  1062.858402
4        Website_Visits    15.277759
0                TV_Ads     0.301281
1      Social_Media_Ads     0.117998
2  Influencer_Marketing    -0.163369